baseURL = 'https://joshuapritikin.com/'
languageCode = 'en-us'
title = 'Joshua Pritikin Counseling'
theme = "hugo-book"

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe= true

[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com/jpritikin/coach'
  BookSearch = false
  [params.Author]
    name = "Joshua N. Pritikin"
    email = "bro@joshuapritikin.com"

languageCode = "en-us"
