baseURL = 'https://estrelacounseling.com/'
languageCode = 'en-us'
title = 'Estrela Counseling'
theme = "hugo-book"

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe= true

[params]
  BookTheme = 'light'
  BookRepo = 'https://github.com/jpritikin/coach'
  BookSearch = false

languageCode = "en-us"

[Author]
    name = "Joshua N. Pritikin"
    email = "bro@estrelacounseling.com"
